name: polandball
description: Fun with countryballs

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.9.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  photo_view: ^0.10.3
  share_extend: ^1.1.9
  flutter_bloc: ^6.1.1
  cached_network_image: ^2.4.1
  equatable: ^1.2.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mali
      fonts:
        - asset: assets/fonts/Mali/Mali-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Mali/Mali-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Mali/Mali-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/Mali/Mali-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Mali/Mali-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Mali/Mali-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Mali/Mali-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Mali/Mali-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Mali/Mali-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Mali/Mali-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Mali/Mali-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Mali/Mali-SemiBoldItalic.ttf
          style: italic
          weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
